language: python
matrix:
  include:
    - python: "2.7"
      env: NOSE_IGNORE_FILES=test_py3_sugar.py
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
services: mongodb
install:
  - pip install -r requirements-test.txt
script:
  - "flake8"
  - "NANOMONGO_SKIP_MOTOR=1 nosetests"
